# Generated by Django 6.1.2 on 2026-10-07 22:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('junction_id', models.CharField(db_index=True, max_length=16)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('direction', models.CharField(blank=True, max_length=16, null=True)),
                ('previous_state', models.CharField(blank=True, max_length=32, null=True)),
                ('new_state', models.CharField(blank=True, max_length=32, null=True)),
                ('command_id', models.CharField(blank=True, max_length=64, null=True)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Junction',
            fields=[
                ('junction_id', models.CharField(help_text="Unique identifier, e.g., 'A'", max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Main Factory Intersection A', max_length=64)),
                ('mode', models.CharField(choices=[('AUTOMATIC', 'AUTOMATIC'), ('MANUAL', 'MANUAL'), ('EMERGENCY', 'EMERGENCY'), ('DEGRADED', 'DEGRADED')], default='AUTOMATIC', max_length=16)),
                ('current_phase', models.CharField(choices=[('NORTH_SOUTH', 'NORTH_SOUTH'), ('EAST_WEST', 'EAST_WEST'), ('ALL_RED_CLEARING', 'ALL_RED_CLEARING')], default='NORTH_SOUTH', max_length=32)),
                ('target_phase', models.CharField(blank=True, choices=[('NORTH_SOUTH', 'NORTH_SOUTH'), ('EAST_WEST', 'EAST_WEST'), ('ALL_RED_CLEARING', 'ALL_RED_CLEARING')], max_length=32, null=True)),
                ('transition_step', models.CharField(choices=[('STEADY', 'STEADY'), ('YELLOW_CLEARING', 'YELLOW_CLEARING'), ('ALL_RED_CLEARING', 'ALL_RED_CLEARING')], default='STEADY', max_length=32)),
                ('phase_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('step_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('desired_north', models.CharField(default='GREEN', max_length=16)),
                ('desired_south', models.CharField(default='GREEN', max_length=16)),
                ('desired_east', models.CharField(default='RED', max_length=16)),
                ('desired_west', models.CharField(default='RED', max_length=16)),
                ('actual_north', models.CharField(default='GREEN', max_length=16)),
                ('actual_south', models.CharField(default='GREEN', max_length=16)),
                ('actual_east', models.CharField(default='RED', max_length=16)),
                ('actual_west', models.CharField(default='RED', max_length=16)),
                ('controller_status', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE'), ('DEGRADED', 'DEGRADED'), ('UNKNOWN', 'UNKNOWN')], default='ONLINE', max_length=16)),
                ('pending_command_id', models.CharField(blank=True, max_length=64, null=True)),
                ('manual_requested_direction', models.CharField(blank=True, max_length=16, null=True)),
                ('manual_expires_at', models.DateTimeField(blank=True, null=True)),
                ('emergency_direction', models.CharField(blank=True, max_length=16, null=True)),
                ('emergency_active', models.BooleanField(default=False)),
                ('green_duration', models.FloatField(default=30.0)),
                ('yellow_duration', models.FloatField(default=5.0)),
                ('all_red_duration', models.FloatField(default=2.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('event_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('junction_id', models.CharField(db_index=True, max_length=16)),
                ('direction', models.CharField(blank=True, max_length=16, null=True)),
                ('event_type', models.CharField(max_length=32)),
                ('vehicle_id', models.CharField(blank=True, max_length=64, null=True)),
                ('sequence_no', models.IntegerField(default=0)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ControllerCommand',
            fields=[
                ('command_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=16)),
                ('requested_state', models.CharField(max_length=16)),
                ('status', models.CharField(default='PENDING', max_length=16)),
                ('actual_state', models.CharField(blank=True, max_length=16, null=True)),
                ('dispatched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('junction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='junctions.junction')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('NORTH', 'NORTH'), ('SOUTH', 'SOUTH'), ('EAST', 'EAST'), ('WEST', 'WEST')], max_length=16)),
                ('vehicle_id', models.CharField(max_length=64)),
                ('vehicle_type', models.CharField(choices=[('EMERGENCY', 'EMERGENCY'), ('TRUCK', 'TRUCK'), ('FORKLIFT', 'FORKLIFT'), ('EMPLOYEE_VEHICLE', 'EMPLOYEE_VEHICLE')], default='EMPLOYEE_VEHICLE', max_length=32)),
                ('sequence_no', models.IntegerField(default=0)),
                ('sensor_timestamp', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('junction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='junctions.junction')),
            ],
            options={
                'ordering': ['arrived_at'],
                'indexes': [models.Index(fields=['junction', 'direction'], name='junctions_v_junctio_4b911f_idx'), models.Index(fields=['junction', 'vehicle_id'], name='junctions_v_junctio_2dbd1f_idx')],
            },
        ),
    ]
